name: Test and build
on:
  pull_request:
    types: [opened]
  push:
jobs:
  tests:
    name: Test with go version ${{ matrix.go_version }} on OS ${{matrix.os}} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.18]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use golang ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: Go version
        run: go version
      - name: Go get dependencies
        run: go get -v -t -d ./...
      - name: Run tests
        run: make test
      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
